- name: vars_prompt example 
  hosts: localhosts
  connection: local 
  vars_prompt:
  - name: username
    prompt: enter your username
    private: false

  - name: password
    prompt: enter your password
    private: true 

  tasks:
  - name : vars prompt example 
    ansible.builtin.debug:
      msg: 
        - " your username is {{username}}"
        -  " your password is {{password}}"