- name: installing packages using loops
  hosts: localhost
  connection: local
  tasks:
  - name : loops 
    ansible.builtin.packages:
      name: "{{item}}"
      state: present
    loop:
    - nginx
    - mysql
    - zip 