- name : install  packages
  hosts: localhost
  connection: local
  tasks :
  - name: loops
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: "mysql", state: "absent"}
    - {name: "nginx", state: "present"}